services:
  copy:
    container_name: copy
    build:
      context: .
      dockerfile: docker/copy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
    develop:
      watch:
        - action: rebuild
          path: ./server
  multistage:
    container_name: multistage
    build:
      context: .
      dockerfile: docker/multistage/Dockerfile
    ports:
      - "8888:8080"
    environment:
      - GIN_MODE=debug
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: main.go
