services:
  copy:
    container_name: copy
    build:
      context: .
      dockerfile: docker/copy/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=debug
    develop:
      watch:
        - action: rebuild
          path: ./server
  copy-build:
    container_name: copy-build
    build:
      context: .
      dockerfile: docker/copy/Dockerfile.dev
    volumes:
      - .:/app
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: go.sum
        - action: rebuild
          path: main.go
  multistage:
    container_name: multistage
    build:
      context: .
      dockerfile: docker/multistage/Dockerfile
    ports:
      - "8888:8080"
    environment:
      - GIN_MODE=debug
    develop:
      watch:
        - action: rebuild
          path: go.mod
        - action: rebuild
          path: main.go
